### ISSUE TITLE
Include not generating Arabic text

### ISSUE THREAD

**Issue by mustafazaki** [vanetix/grunt-includes#33]
I am using Arabic in my site and when I put Arabic words include is generating as "???????"

**Comment by vanetix** [comment]
This is odd, there shouldn't be any issues with building anything since its just regular expressions and replacements. Could you create or provide a test case that produces this output?

**Comment by mustafazaki** [comment]
Thanks for your reply I tell you even strange thing that I use includes for Arabic  before and its was generating fine output but in my current project I faced this issue after some struggle I manage to solve the issue by copy pasting the files from my previous project its strange but working for me.

In this link https://dl.dropboxusercontent.com/u/41150793/test.zip there is 2 files one is footer-ar.html which i copied from my previous project and second is send-application-widget.html which i create during development you can download the folder and test it.

I used Webstorm 10 in both of my project and visualstudionline as a Vcs

Thanks
