### ISSUE TITLE
Problem whith install

### ISSUE THREAD

**Issue by VaskaDogana** [vanetix/grunt-includes#42]
Hi, I tryed install Your package, but have error, there wrote about version Grunt 1.0.0 (as far as I understand), but in description plugin wrote "Requires grunt ~0.4.0"
Please help me, what is wrong?
This is log:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'grunt-includes',
1 verbose cli   '--save-dev' ]
2 info using npm@2.15.9
3 info using node@v4.6.1
4 verbose install initial load of D:\work\package.json
5 warn package.json example-project@0.1.0 No description
6 warn package.json example-project@0.1.0 No repository field.
7 warn package.json example-project@0.1.0 No README data
8 warn package.json example-project@0.1.0 No license field.
9 verbose installManyTop reading scoped package data from D:\work\node_modules\grunt\package.json
10 verbose installManyTop reading scoped package data from D:\work\node_modules\grunt-autoprefixer\package.json
11 verbose installManyTop reading scoped package data from D:\work\node_modules\grunt-concurrent\package.json
12 verbose installManyTop reading scoped package data from D:\work\node_modules\grunt-contrib-concat\package.json
13 verbose installManyTop reading scoped package data from D:\work\node_modules\grunt-contrib-imagemin\package.json
14 verbose installManyTop reading scoped package data from D:\work\node_modules\grunt-contrib-sass\package.json
15 verbose installManyTop reading scoped package data from D:\work\node_modules\grunt-contrib-uglify\package.json
16 verbose installManyTop reading scoped package data from D:\work\node_modules\grunt-contrib-watch\package.json
17 verbose installManyTop reading scoped package data from D:\work\node_modules\grunt-includes\package.json
18 verbose installManyTop reading scoped package data from D:\work\node_modules\grunt-spritesmith\package.json
19 verbose installManyTop reading scoped package data from D:\work\node_modules\time-grunt\package.json
20 info package.json grunt@0.4.5 No license field.
21 verbose readDependencies loading dependencies from D:\work\package.json
22 verbose install grunt-includes is installed as 1.0.0
23 silly cache add args [ 'grunt-includes', null ]
24 verbose cache add spec grunt-includes
25 silly cache add parsed spec Result {
25 silly cache add   raw: 'grunt-includes',
25 silly cache add   scope: null,
25 silly cache add   name: 'grunt-includes',
25 silly cache add   rawSpec: '',
25 silly cache add   spec: 'latest',
25 silly cache add   type: 'tag' }
26 silly addNamed grunt-includes@latest
27 verbose addNamed "latest" is being treated as a dist-tag for grunt-includes
28 info addNameTag [ 'grunt-includes', 'latest' ]
29 silly mapToRegistry name grunt-includes
30 silly mapToRegistry using default registry
31 silly mapToRegistry registry https://registry.npmjs.org/
32 silly mapToRegistry data Result {
32 silly mapToRegistry   raw: 'grunt-includes',
32 silly mapToRegistry   scope: null,
32 silly mapToRegistry   name: 'grunt-includes',
32 silly mapToRegistry   rawSpec: '',
32 silly mapToRegistry   spec: 'latest',
32 silly mapToRegistry   type: 'tag' }
33 silly mapToRegistry uri https://registry.npmjs.org/grunt-includes
34 verbose addNameTag registry:https://registry.npmjs.org/grunt-includes not in flight; fetching
35 verbose request uri https://registry.npmjs.org/grunt-includes
36 verbose request no auth needed
37 info attempt registry request try #1 at 21:32:36
38 verbose request id 47ba2862add330c1
39 verbose etag "8MMZW1F8D1ZXVBHQMROMJP1EQ"
40 http request GET https://registry.npmjs.org/grunt-includes
41 http 304 https://registry.npmjs.org/grunt-includes
42 verbose headers { date: 'Mon, 31 Oct 2016 19:32:37 GMT',
42 verbose headers   via: '1.1 varnish',
42 verbose headers   'cache-control': 'max-age=300',
42 verbose headers   etag: '"8MMZW1F8D1ZXVBHQMROMJP1EQ"',
42 verbose headers   age: '282',
42 verbose headers   connection: 'keep-alive',
42 verbose headers   'x-served-by': 'cache-fra1240-FRA',
42 verbose headers   'x-cache': 'HIT',
42 verbose headers   'x-cache-hits': '1',
42 verbose headers   'x-timer': 'S1477942357.251624,VS0,VE0',
42 verbose headers   vary: 'Accept-Encoding' }
43 silly get cb [ 304,
43 silly get   { date: 'Mon, 31 Oct 2016 19:32:37 GMT',
43 silly get     via: '1.1 varnish',
43 silly get     'cache-control': 'max-age=300',
43 silly get     etag: '"8MMZW1F8D1ZXVBHQMROMJP1EQ"',
43 silly get     age: '282',
43 silly get     connection: 'keep-alive',
43 silly get     'x-served-by': 'cache-fra1240-FRA',
43 silly get     'x-cache': 'HIT',
43 silly get     'x-cache-hits': '1',
43 silly get     'x-timer': 'S1477942357.251624,VS0,VE0',
43 silly get     vary: 'Accept-Encoding' } ]
44 verbose etag https://registry.npmjs.org/grunt-includes from cache
45 verbose get saving grunt-includes to C:\Users\Vasya\AppData\Roaming\npm-cache\registry.npmjs.org\grunt-includes\.cache.json
46 verbose correctMkdir C:\Users\Vasya\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
47 silly addNameTag next cb for grunt-includes with tag latest
48 silly addNamed grunt-includes@1.0.0
49 verbose addNamed "1.0.0" is a plain semver version for grunt-includes
50 silly cache afterAdd grunt-includes@1.0.0
51 verbose afterAdd C:\Users\Vasya\AppData\Roaming\npm-cache\grunt-includes\1.0.0\package\package.json not in flight; writing
52 verbose correctMkdir C:\Users\Vasya\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
53 verbose afterAdd C:\Users\Vasya\AppData\Roaming\npm-cache\grunt-includes\1.0.0\package\package.json written
54 silly install resolved [ { name: 'grunt-includes',
54 silly install resolved     description: 'Include other files within a file.',
54 silly install resolved     version: '1.0.0',
54 silly install resolved     author: { name: 'vanetix', email: 'matmcfarland@gmail.com' },
54 silly install resolved     license: 'MIT',
54 silly install resolved     main: 'Gruntfile.js',
54 silly install resolved     homepage: 'https://github.com/vanetix/grunt-includes',
54 silly install resolved     bugs: { url: 'https://github.com/vanetix/grunt-includes/issues' },
54 silly install resolved     repository:
54 silly install resolved      { type: 'git',
54 silly install resolved        url: 'git://github.com/vanetix/grunt-includes.git' },
54 silly install resolved     scripts: { test: 'grunt test' },
54 silly install resolved     devDependencies:
54 silly install resolved      { grunt: '^1.0.1',
54 silly install resolved        'grunt-contrib-clean': '^1.0.0',
54 silly install resolved        'grunt-contrib-jshint': '^1.0.0',
54 silly install resolved        'grunt-contrib-nodeunit': '^1.0.0' },
54 silly install resolved     peerDependencies: { grunt: '>=1.0.0' },
54 silly install resolved     keywords: [ 'include', 'gruntplugin' ],
54 silly install resolved     engines: { node: '>= 0.8.0' },
54 silly install resolved     files: [ 'tasks/includes.js' ],
54 silly install resolved     gitHead: 'afc3961a141234784850ab13a8cab88f5bc4fcdf',
54 silly install resolved     _id: 'grunt-includes@1.0.0',
54 silly install resolved     _shasum: 'c22d660cd69507acfb931608b70e36fb3a626b00',
54 silly install resolved     _from: 'grunt-includes@latest',
54 silly install resolved     _npmVersion: '3.8.7',
54 silly install resolved     _nodeVersion: '5.11.0',
54 silly install resolved     _npmUser: { name: 'vanetix', email: 'matmcfarland@gmail.com' },
54 silly install resolved     maintainers: [ [Object] ],
54 silly install resolved     dist:
54 silly install resolved      { shasum: 'c22d660cd69507acfb931608b70e36fb3a626b00',
54 silly install resolved        tarball: 'https://registry.npmjs.org/grunt-includes/-/grunt-includes-1.0.0.tgz' },
54 silly install resolved     _npmOperationalInternal:
54 silly install resolved      { host: 'packages-16-east.internal.npmjs.com',
54 silly install resolved        tmp: 'tmp/grunt-includes-1.0.0.tgz_1461767490421_0.9741134929936379' },
54 silly install resolved     directories: {},
54 silly install resolved     _resolved: 'https://registry.npmjs.org/grunt-includes/-/grunt-includes-1.0.0.tgz',
54 silly install resolved     readme: 'ERROR: No README data found!' } ]
55 info install grunt-includes@1.0.0 into D:\work
56 info installOne grunt-includes@1.0.0
57 verbose installOne of grunt-includes to D:\work not in flight; installing
58 verbose correctMkdir C:\Users\Vasya\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
59 verbose lock using C:\Users\Vasya\AppData\Roaming\npm-cache\_locks\grunt-includes-548d44f774f642a9.lock for D:\work\node_modules\grunt-includes
60 silly install write writing grunt-includes 1.0.0 to D:\work\node_modules\grunt-includes
61 verbose unbuild node_modules\grunt-includes
62 info preuninstall grunt-includes@1.0.0
63 info uninstall grunt-includes@1.0.0
64 verbose unbuild rmStuff grunt-includes@1.0.0 from D:\work\node_modules
65 info postuninstall grunt-includes@1.0.0
66 silly gentlyRm D:\work\node_modules\grunt-includes is being purged from base D:\work
67 verbose gentlyRm don't care about contents; nuking D:\work\node_modules\grunt-includes
68 silly vacuum-fs purging D:\work\node_modules\grunt-includes
69 silly vacuum-fs quitting because other entries in D:\work\node_modules
70 verbose tar unpack C:\Users\Vasya\AppData\Roaming\npm-cache\grunt-includes\1.0.0\package.tgz
71 verbose tar unpacking to D:\work\node_modules\grunt-includes
72 silly gentlyRm D:\work\node_modules\grunt-includes is being purged
73 verbose gentlyRm don't care about contents; nuking D:\work\node_modules\grunt-includes
74 silly gunzTarPerm modes [ '777', '666' ]
75 silly gunzTarPerm extractEntry package.json
76 silly gunzTarPerm modified mode [ 'package.json', 420, 438 ]
77 silly gunzTarPerm extractEntry Gruntfile.js
78 silly gunzTarPerm modified mode [ 'Gruntfile.js', 420, 438 ]
79 silly gunzTarPerm extractEntry Readme.md
80 silly gunzTarPerm modified mode [ 'Readme.md', 420, 438 ]
81 silly gunzTarPerm extractEntry License
82 silly gunzTarPerm modified mode [ 'License', 420, 438 ]
83 silly gunzTarPerm extractEntry tasks/includes.js
84 silly gunzTarPerm modified mode [ 'tasks/includes.js', 420, 438 ]
85 verbose write writing to D:\work\node_modules\grunt-includes\package.json
86 info preinstall grunt-includes@1.0.0
87 verbose readDependencies loading dependencies from D:\work\node_modules\grunt-includes\package.json
88 silly prepareForInstallMany adding grunt@>=1.0.0 from grunt-includes peerDependencies
89 warn peerDependencies The peer dependency grunt@>=1.0.0 included from grunt-includes will no
90 warn peerDependencies longer be automatically installed to fulfill the peerDependency
91 warn peerDependencies in npm 3+. Your application will need to depend on it explicitly.
92 verbose readDependencies loading dependencies from D:\work\node_modules\grunt-includes\package.json
93 silly install resolved []
94 verbose about to build D:\work\node_modules\grunt-includes
95 info build D:\work\node_modules\grunt-includes
96 info linkStuff grunt-includes@1.0.0
97 silly linkStuff grunt-includes@1.0.0 has D:\work\node_modules as its parent node_modules
98 verbose linkBins grunt-includes@1.0.0
99 verbose linkMans grunt-includes@1.0.0
100 verbose rebuildBundles grunt-includes@1.0.0
101 info install grunt-includes@1.0.0
102 info postinstall grunt-includes@1.0.0
103 verbose readDependencies loading dependencies from D:\work\package.json
104 verbose targetResolver reading package data from D:\work\node_modules\grunt\package.json
105 verbose targetResolver reading package data from D:\work\node_modules\grunt-autoprefixer\package.json
106 verbose targetResolver reading package data from D:\work\node_modules\grunt-concurrent\package.json
107 verbose targetResolver reading package data from D:\work\node_modules\grunt-contrib-concat\package.json
108 verbose targetResolver reading package data from D:\work\node_modules\grunt-contrib-imagemin\package.json
109 verbose targetResolver reading package data from D:\work\node_modules\grunt-contrib-sass\package.json
110 verbose targetResolver reading package data from D:\work\node_modules\grunt-contrib-uglify\package.json
111 verbose targetResolver reading package data from D:\work\node_modules\grunt-contrib-watch\package.json
112 verbose targetResolver reading package data from D:\work\node_modules\grunt-includes\package.json
113 verbose targetResolver reading package data from D:\work\node_modules\grunt-spritesmith\package.json
114 verbose targetResolver reading package data from D:\work\node_modules\time-grunt\package.json
115 verbose already installed skipping grunt@>=1.0.0 D:\work
116 silly install resolved []
117 verbose unlock done using C:\Users\Vasya\AppData\Roaming\npm-cache\_locks\grunt-includes-548d44f774f642a9.lock for D:\work\node_modules\grunt-includes
118 verbose validateInstall loading D:\work\package.json for validation
119 verbose stack Error: The package grunt@0.4.5 does not satisfy its siblings' peerDependencies requirements!
119 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:125:32
119 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:268:7
119 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:142:5
119 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:263:14
119 verbose stack     at cb (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
119 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:263:14
119 verbose stack     at cb (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
119 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:263:14
119 verbose stack     at cb (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
119 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:263:14
120 verbose cwd D:\work
121 error Windows_NT 6.1.7601
122 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "grunt-includes" "--save-dev"
123 error node v4.6.1
124 error npm  v2.15.9
125 error code EPEERINVALID
126 error peerinvalid The package grunt@0.4.5 does not satisfy its siblings' peerDependencies requirements!
126 error peerinvalid Peer grunt-includes@1.0.0 wants grunt@>=1.0.0
126 error peerinvalid Peer grunt-autoprefixer@3.0.4 wants grunt@>=0.4.2
126 error peerinvalid Peer grunt-contrib-concat@1.0.1 wants grunt@>=0.4.0
126 error peerinvalid Peer grunt-contrib-sass@1.0.0 wants grunt@>=0.4.0
126 error peerinvalid Peer grunt-concurrent@2.3.1 wants grunt@>=0.4.0
127 verbose exit [ 1, true ]

**Comment by vanetix** [comment]
Looks like I forgot to update the documentation, change your grunt dependency to the current version and that should take care of the issue.

**Comment by VaskaDogana** [comment]
Thanks
